### ISSUE TITLE
Problems when using Maiar app

### ISSUE THREAD

**Issue by juliancwirko** [multiversx/mx-sdk-js-web-wallet-provider#9]
I tested https://dapp-template.elrond.com The flow: 

1. Choose Web Wallet (login)
2. On the Web Wallet side, use Maiar app
3. Redirect to the dapp-template app
4. Ping transaction
5. Sign in using Maiar App when on the Web Wallet page
6. Web wallet displays `Rejected by user`

More details here: https://github.com/ElrondNetwork/dapp-template/issues/46#issuecomment-1307130062

Android, Maiar 1.5.46

**Comment by CiprianDraghici** [comment]
This is a known issue. It will be fixed in the new web wallet version

**Comment by schimih** [comment]
Issue fixed with the new web wallet version.
